"""this migration creates a user confirmatiom column inside the user model

Revision ID: 0a6097e95c21
Revises: 78d6bc43a53c
Create Date: 2018-05-27 11:42:40.322903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6097e95c21'
down_revision = '78d6bc43a53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
