"""this migration updates the blog model

Revision ID: 3daa517490e3
Revises: 84c85b166dbd
Create Date: 2018-05-27 20:12:06.442936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daa517490e3'
down_revision = '84c85b166dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_blogs_timestamp'), 'blogs', ['timestamp'], unique=False)
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['id'])
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_blogs_timestamp'), table_name='blogs')
    op.drop_column('blogs', 'timestamp')
    op.drop_column('blogs', 'author_id')
    # ### end Alembic commands ###
