"""this migration creates the blog table

Revision ID: 974e751d201e
Revises: 
Create Date: 2018-05-25 16:01:02.709666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974e751d201e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
